### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by BCaven** [BCaven/creativity-optional#11]
Look at [this](https://stackoverflow.com/questions/28985714/run-apps-using-audio-in-a-docker-container) for getting audio in the docker container.

[docker documentation](https://docs.docker.com/guides/get-started/)

# Tasks
- [x] create a docker container
- [x] get audio input
- [x] build loopback devices from docker container (might be a script that runs then launches the docker container)
- [ ] output pipeline
- [ ] get peripheral devices from host machine

**Comment by BCaven** [comment]
[this](https://github.com/TheBiggerGuy/docker-pulseaudio-example) person did it with pulse audio

**Comment by BCaven** [comment]
we might have a problem making a cross-platform [Docker] container use host system audio as described [here](https://stackoverflow.com/questions/52890474/how-to-get-docker-audio-and-input-with-windows-or-mac-host) on windows and [here](https://apple.stackexchange.com/questions/47822/where-are-audio-device-files-in-osx) for OSX, although I think getting audio into the docker container is going to be much more challenging than expected regardless.

[here is an older stackoverflow question about this topic for MacOS](https://stackoverflow.com/questions/41083436/how-to-play-sound-in-a-docker-container-on-mac-os-yosemite)

The good news about using a docker container is that we will be running a linux VM so the *rest* of the application should not have to worry about it, provided we actually get the system audio on that OS.

**Comment by BCaven** [comment]
Going to use [compose](https://docs.docker.com/get-started/08_using_compose/) to make the Docker process easier to interact with.

**Comment by BCaven** [comment]
Running Docker containers with GUIs: 
[stackoverflow question about pyqt](https://stackoverflow.com/questions/24095968/docker-for-gui-based-environments) 
[github repo that does it for Linux and Mac with pyqt5](https://github.com/jozo/docker-pyqt5)

I think this is a "worse" solution than having the docker app present a webapp because it would be difficult to make this GUI work across platforms

**Comment by BCaven** [comment]
Original task list is now largely obsolete.
At the moment the application is using a local python script to act as the client for the server which runs in the docker container. Look at #15 for more info

**Comment by BCaven** [comment]
switching to [soundcard](https://github.com/bastibe/SoundCard) instead of [pyaudio](https://people.csail.mit.edu/hubert/pyaudio/docs/) effectively removes the need for generated loopback devices because they are built into the library.
